#!/bin/sh
# easy-signing-party: simple utilities used to do a signing party
# Copyright (C) 2017  Iru Cai <mytbk920423@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# usage: do_signing <yourkeyid> <keyid>

TEMPDIR="$(mktemp -d)"
MYKEY="$1"
KEYTOSIGN="${2/0[xX]}"

echo "Temporary files saved at $TEMPDIR"

# first, sign the key
gpg --sign-with "$MYKEY" --sign-key "$KEYTOSIGN"
gpg --export "$KEYTOSIGN" > "$TEMPDIR/$KEYTOSIGN.pub"

# then extract all the uid
mkdir "$TEMPDIR/uid"
extract_key "$TEMPDIR/$KEYTOSIGN.pub" "$MYKEY" "$KEYTOSIGN" "$TEMPDIR/uid"

# encrypt them, also encrypt to myself, then send it

source "$TEMPDIR/uid/mails"

for i in $(seq 0 $((${#MAILS[@]}-1)))
do
   FILENAME=$(printf "$TEMPDIR/uid/$KEYTOSIGN.%02d" $i)
   gpg --enarmor "$FILENAME"
   echo "sending mail to ${MAILS[$i]}"
   cat template.txt "$FILENAME.asc" | \
       gpg --armor --recipient "$MYKEY" --recipient "$KEYTOSIGN" --encrypt | \
       msmtp ${MAILS[$i]}
done
